language: node_js

node_js:
- '6'

sudo: false

cache:
  directories:
  - node_modules

git:
  depth: 1

before_script:
- chmod +x .travis/after_success.sh
- chmod +x ./deploy

script:
- npm test

branches:
  except:
  - gh-pages

env:
  global:
  - REPO="git@github.com:jessy1092/resume"
  - secure: wwcI4zNGh9kT+YYSkqm4LqaTG/+7GNfCBV1egpBAYv9Cv9NB5Q6fc+8lBNU5kVIdAhih+TS56+fKCxbsL97mGP2ctqdaX8DIeaPnWGOnPGUS5eO9TJO37I8hgjkn4KBHyO6MsG0YMzr7bFwAw9/53JHn+BzVJ4t+fiqDlMr/JWtdfdQYJLUHdgL7oMLxufAsLG/gMx1Zd6S5bifkM+HI1DugIAwv7UPVCVMYnMjxkl/d6TafrbZqYb0rCDT2p+Dtic2wsT7io/hTs2ZgZ3Ug+Uc0FZVcoWM7gvWA4PeYHNy9AbufqFcKKHhK7v5nd1D8yOyWwc/ie2fkeG1zimiokFPchkzqnG1UYzIv2vLYf9AjDZ7rrgPbcZj9ZMi9eA/TKX17Xf9F/HP8RS3UFADsTjU02ta3ha0LmZvkz5SzMruwsFsjGFFXs2Mr3W7kiNwMSNXwgiCSMA+qstsng8Q8jcBrg0pklcZm33zKweVb+Otr8rQ+A9bk2SFOEpIN5odP0FTouu4ZulEoyR5BIHqsdk+BpSILHTQOxEPSHXuFxv6Z7AvOw5kkdy/96tEejyD901NIasLWa08V29k1PRCyrayISy0DA9r9njpAZUEsobn4EaV/VMejBZCEU2jeqqYOGhKyx+IjiLQT0W4uHFhOrcfH9H9JW3hM7zHlNi+sXHg=

after_success: .travis/after_success.sh
