language: node_js

node_js:
- '6'

sudo: false

cache:
  directories:
  - node_modules

git:
  depth: 1

before_script:
- chmod +x .travis/after_success.sh
- chmod +x ./deploy

script:
- npm test

branches:
  except:
  - gh-pages

env:
  global:
  - REPO="git@github.com:jessy1092/resume"

after_success: .travis/after_success.sh
