name: "Publish Resume"
on:
  push:
    branches:
      - master

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install the dependencies
        run: yarn

      - name: Build the resume
        run: |
          mkdir -p public
          yarn build
          cp CNAME public/

      - name: Deploy to the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public